epoch:0, iteration:0, train loss:2.90
accuracy:10.16%
epoch:0, iteration:50, train loss:0.87
accuracy:23.44%
epoch:0, iteration:100, train loss:0.80
accuracy:37.50%
epoch:0, iteration:150, train loss:0.66
accuracy:74.22%
epoch:0, iteration:200, train loss:0.59
accuracy:71.88%
epoch:0, iteration:250, train loss:0.52
accuracy:81.25%
epoch:0, iteration:300, train loss:0.46
accuracy:88.28%
epoch:0, iteration:350, train loss:0.41
accuracy:86.72%
epoch:0, iteration:400, train loss:0.39
accuracy:87.50%
epoch:0, iteration:450, train loss:0.37
accuracy:90.62%
Traceback (most recent call last):
  File "/media/mllab/yym/code/3/snn/NMNIST_training.py", line 128, in <module>
    train(train_loader, test_loader, net)
  File "/media/mllab/yym/code/3/snn/NMNIST_training.py", line 116, in train
    output = net(data)
  File "/home/yym/.conda/envs/yymnip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yym/.conda/envs/yymnip/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/yym/.conda/envs/yymnip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yym/.conda/envs/yymnip/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/yym/.conda/envs/yymnip/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [31, 128, 2, 34, 34]
